---
- name: User Management Playbook
  hosts: all
  tasks:
    - name: Add a new user
      user:
        name: "{{ new_username }}"
        password: "{{ new_user_password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
      when: new_username|length > 0
        
    - name: Remove a user
      user:
        name: "{{ username_to_remove }}"
        state: absent
      when: username_to_remove|length > 0
