---
- name: User Management Playbook
  hosts: all
  tasks:
    - name: Add a new user
      user:
        name: "{{ new_username }}"
        password: " {{ new_user_password }}"
        shell: /bin/bash
        state: present
