---
- name: User Management Playbook
  hosts: all
  tasks:
    - name: Add a new user
      user:
        name: "{{ new_username }}"
        password: "{{ new_user_password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
      when: new_username|length > 0
        
    - name: Remove a user
      user:
        name: "{{ username_to_remove }}"
        state: absent
      when: username_to_remove|length > 0
      
    - name: Modify user properties
      user:
        name: "{{ username_to_modify }}"
        shell: "{{ new_user_shell }}"
        groups: "{{ new_user_groups }}"
        append: yes
        state: present
      when: username_to_modify|length > 0

    - name: Grant sudo access
      become: yes
      lineinfile:
        dest: /etc/sudoers
        regexp: '^{{ username_to_grant_sudo }}'
        line: '{{ username_to_grant_sudo }} ALL=(ALL:ALL) NOPASSWD: ALL'
        state: present
      when: username_to_grant_sudo|length > 0

    - name: Revoke sudo access
      become: yes
      lineinfile:
        dest: /etc/sudoers
        regexp: '^{{ username_to_revoke }}'
        state: absent
      when: username_to_revoke|length > 0

